name: 🐞 Bug Report
description: Create a report about something that is not working
body:
- type: markdown
  attributes:
    value: |
      More information on our issue management policies can be found here: https://aka.ms/aspnet/issue-policies

      Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting **non-security** bugs and feature requests.

      If you believe you have an issue that affects the SECURITY of the platform, please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://www.microsoft.com/en-us/msrc/bounty-dot-net-core) but ONLY if it is reported through email.
      For other types of questions, consider using [StackOverflow](https://stackoverflow.com).
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered ([lucifron/issues](https://github.com/sventhiel/Lucifron/issues?q=is%3Aissue)).
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: |
      Steps to reproduce the behavior.
  validations:
    required: false
- type: textarea
  attributes:
    label: Exceptions (if any)
    description: Include the exception you get when facing this issue.
    placeholder: 
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
