name: 🐞 Bug Report
description: You discovered something that does not work as desired/expected? Please report that bug!
labels: 'type: bug report'
assignees: sventhiel
body:
- type: markdown
  attributes:
    value: |
      Please provide as much information as possible about the bug.
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please check the existing issues first, to see if an issue already exists for the bug you encountered ([lucifron/issues](https://github.com/sventhiel/lucifron/issues?q=is%3Aissue)).
    options:
    - label: "I searched for a similar issue and didn't find a suitable one."
      required: true
- type: textarea
  attributes:
    label: What is going wrong? 
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: How is it supposed to work?
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: How can it be reproduced? 
    description: Steps to reproduce the behavior.
    value: |
    
  validations:
    required: false
- type: textarea
  attributes:
    label: Do you get any exceptions?
    description:       
  validations:
    required: false
- type: textarea
  attributes:
    label: What kind of system do you use?
    description:       
  validations:
    required: false
- type: textarea
  attributes:
    label: Task(s)
    description: Include the exception you get when facing this issue.
    placeholder: 
  validations:
    required: false
