name: 🐞 Bug Report
description: You discovered something that does not work as desired/expected? Please report that bug!
labels: 'type: bug report'
assignees: sventhiel
body:
- type: markdown
  attributes:
    value: |
      Some more information in here!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered ([lucifron/issues](https://github.com/sventhiel/lucifron/issues?q=is%3Aissue)). More information on our issue management policies is available [here](https://aka.ms/aspnet/issue-policies).
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: false
- type: textarea
  attributes:
    label: Exceptions (if any)
    description: Include the exception you get when facing this issue.
    placeholder: 
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Work Items
      
      Those will be added by maintainers and so on.
