name: 🚀 Enhancement
description: In general, you are happy with a feature but .
labels: 'type: enhancement'
assignees: sventhiel
body:
- type: markdown
  attributes:
    value: |
      More information on our issue management policies can be found here: https://aka.ms/aspnet/issue-policies

      Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting **non-security** bugs and feature requests.

      If you believe you have an issue that affects the SECURITY of the platform, please do NOT create an issue and instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://www.microsoft.com/en-us/msrc/bounty-dot-net-core) but ONLY if it is reported through email.
      For other types of questions, consider using [StackOverflow](https://stackoverflow.com).
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please check the existing issues first, to see if an issue already exists for the bug you encountered ([lucifron/issues](https://github.com/sventhiel/lucifron/issues?q=is%3Aissue)).
    options:
    - label: "I searched for a similar issue and didn't find a suitable one."
      required: true
- type: textarea
  attributes:
    label: Describe your question, idea and/or hint.
    description: A clear and concise description of what your question/idea/hint is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Work Items
    description: |
      Hier kommen entsprechende Einträge von uns, die dann als Work Items umgewandelt werden können.
  validations:
    required: false
