name: 💡 Feature Request
description: You have an idea for a new feature (or set of functions)? Please let us know!
labels: 'type: feature request'
assignees: sventhiel
body:
- type: markdown
  attributes:
    value: |
      Please provide as much information as possible about the feature. Beside text, you are able to add images/screenshots as well.
- type: checkboxes
  attributes:
    label: "Is there an existing issue for this?"
    description: "Please search to see if an issue already exists for the feature request ([lucifron/issues](https://github.com/sventhiel/lucifron/issues?q=is%3Aissue))."
    options:
    - label: "I have searched the existing issues."
      required: true
- type: textarea
  attributes:
    label: "What do you miss?"
    description: "A clear and concise description of what your idea is."
  validations:
    required: true
- type: textarea
  attributes:
    label: "How it is supposed to work/look?"
    description: "Please provide further information about your solution."
  validations:
    required: false
- type: textarea
  attributes:
    label: "Do you know a similar solution out there in the wild?"
    description: "You know other systems that support that feature - please share that information with us."
  validations:
    required: false
- type: textarea
  attributes:
    label: "Which task(s) is/are related to this issue?"
    description: "If you have already (small) tasks in mind to fix the bug, please let us know by adding items similar to the placeholder ones. Otherwise we are going to add proper tasks for it later on."
    placeholder: |
      - [ ] add try-catch block
      - [ ] add exception handling
      - [ ] change assignment of variables
      - [ ] ...
  validations:
    required: false
