name: ❓ Question
description: You have a general question, suggestion or hint? Please share it with us!
labels: 'type: question'
assignees: sventhiel
body:
- type: markdown
  attributes:
    value: |
      Please provide as much information as possible about your question.
- type: checkboxes
  attributes:
    label: "Is there an existing issue for this?"
    description: "Please search to see if an issue already exists related to your question ([lucifron/issues](https://github.com/sventhiel/lucifron/issues?q=is%3Aissue))."
    options:
    - label: "I have searched the existing issues."
      required: true
- type: textarea
  attributes:
    label: "What's on your mind?"
    description: "A clear and concise description about your question."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Which task(s) is/are related to this issue?"
    description: "If you have already (small) tasks in mind to fix the bug, please let us know by adding items similar to the placeholder ones. Otherwise we are going to add proper tasks for it later on."
    placeholder: |
      - [ ] add try-catch block
      - [ ] add exception handling
      - [ ] change assignment of variables
      - [ ] ...
  validations:
    required: false
